import { Metadata } from "next"

export const metadata : Metadata = {
  title: 'Posts List',
  description: 'Generated by create next app',
}

export default function Posts({params}: {params : {postId: string}}) {
  return (
    <div className="bg-slate-300">
      <h1>Postingan {params.postId}</h1>
    </div>
  )
}
