import { Metadata } from "next"
import AddProduct from "./addProduct"
import DeleteProduct from "./deleteProduct" 

type Product = {
    id: number,
    title : string,
    price : string
}

export const metadata : Metadata = {
  title: 'Products List',
  description: 'Generated by create next app',
}

const getProducts = async () =>{
    const res = await fetch('http://localhost:5000/products',{
        cache : 'no-store',
    })
    return res.json()
}
export default async function ProductList() {
    const products : Product[] = await getProducts()
    console.log(products)
  return (
    <div className="py-10 px-10">
        <div className="py-2">
            <AddProduct/>
        </div>
        <table className="table w-3/4 text-center">
            <thead className="bg-slate-200 ">
                <tr>
                    <td className="w-10">No</td>
                    <td>Products</td>
                    <td>Price</td>
                    <td>Action</td>
                </tr>
            </thead>
            <tbody>
                {products.map((product,index)=>(
                    <tr key={product.id} className="">
                        <td className="">{index+1}</td>
                        <td>{product.title}</td>
                        <td>{product.price}</td>
                        <td>
                            <DeleteProduct {...product}/>
                        </td>
                    </tr>
                    // <p key={product.id}>{product.title} {product.price}</p>
                ))}
            </tbody>
            
        </table>
    </div>
  )
}
